export { DashboardPage } from "./DashboardPage";
export { LandingPage } from "./LandingPage";
export { LoginPage } from "./LoginPage";
export { SettingsPage } from "./SettingsPage";
export { SignupPage } from "./SignupPage";
export { ServicesPage } from "./ServicesPage";
export { GalleryPage } from "./GalleryPage";
export { AvailabilityPage } from "./AvailabilityPage";
export { SectionsPage } from "./SectionsPage";
